INSERT IGNORE INTO Permission (id, name, slug, grp, description, createdAt) VALUES
  (UUID(), 'View tickets', 'tickets.view', 'Tickets', 'View ticket records and activity.', NOW(3)),
  (UUID(), 'Create tickets', 'tickets.create', 'Tickets', 'Create new ticket records.', NOW(3)),
  (UUID(), 'Edit tickets', 'tickets.edit', 'Tickets', 'Update, assign, and resolve tickets.', NOW(3)),
  (UUID(), 'Delete tickets', 'tickets.delete', 'Tickets', 'Delete ticket records.', NOW(3)),
  (UUID(), 'Approve tickets', 'tickets.approve', 'Tickets', 'Approve ticket changes and service requests.', NOW(3)),
  (UUID(), 'Export tickets', 'tickets.export', 'Tickets', 'Export ticket data.', NOW(3)),
  (UUID(), 'View assets', 'assets.view', 'Assets', 'View asset and device inventory.', NOW(3)),
  (UUID(), 'Create assets', 'assets.create', 'Assets', 'Create asset records.', NOW(3)),
  (UUID(), 'Edit assets', 'assets.edit', 'Assets', 'Update asset records.', NOW(3)),
  (UUID(), 'Delete assets', 'assets.delete', 'Assets', 'Delete or retire asset records.', NOW(3)),
  (UUID(), 'Export assets', 'assets.export', 'Assets', 'Export asset inventory.', NOW(3)),
  (UUID(), 'View users', 'users.view', 'Administration', 'View users and role assignments.', NOW(3)),
  (UUID(), 'Create users', 'users.create', 'Administration', 'Invite and create users.', NOW(3)),
  (UUID(), 'Manage users', 'users.manage', 'Administration', 'Edit, suspend, and assign users.', NOW(3)),
  (UUID(), 'Delete users', 'users.delete', 'Administration', 'Remove users.', NOW(3)),
  (UUID(), 'View roles', 'roles.view', 'Administration', 'View roles and permission assignments.', NOW(3)),
  (UUID(), 'Manage roles', 'roles.manage', 'Administration', 'Create, clone, and edit roles.', NOW(3)),
  (UUID(), 'View billing', 'billing.view', 'Billing', 'View subscription and billing status.', NOW(3)),
  (UUID(), 'Create billing records', 'billing.create', 'Billing', 'Create billing and subscription records.', NOW(3)),
  (UUID(), 'Edit billing', 'billing.edit', 'Billing', 'Change subscriptions and billing settings.', NOW(3)),
  (UUID(), 'Manage billing', 'billing.manage', 'Billing', 'Administer payment providers and billing operations.', NOW(3)),
  (UUID(), 'Approve billing', 'billing.approve', 'Billing', 'Approve billing adjustments and credits.', NOW(3)),
  (UUID(), 'Export billing', 'billing.export', 'Billing', 'Export billing records.', NOW(3)),
  (UUID(), 'View invoices', 'invoices.view', 'Billing', 'View invoices and payment status.', NOW(3)),
  (UUID(), 'Create invoices', 'invoices.create', 'Billing', 'Create invoices.', NOW(3)),
  (UUID(), 'Edit invoices', 'invoices.edit', 'Billing', 'Edit draft invoices.', NOW(3)),
  (UUID(), 'Approve invoices', 'invoices.approve', 'Billing', 'Approve and issue invoices.', NOW(3)),
  (UUID(), 'Export invoices', 'invoices.export', 'Billing', 'Export invoice data.', NOW(3)),
  (UUID(), 'View quotes', 'quotes.view', 'Billing', 'View quotes.', NOW(3)),
  (UUID(), 'Create quotes', 'quotes.create', 'Billing', 'Create quotes.', NOW(3)),
  (UUID(), 'Edit quotes', 'quotes.edit', 'Billing', 'Edit quotes.', NOW(3)),
  (UUID(), 'Approve quotes', 'quotes.approve', 'Billing', 'Approve quotes.', NOW(3)),
  (UUID(), 'Export quotes', 'quotes.export', 'Billing', 'Export quote data.', NOW(3)),
  (UUID(), 'View dispatch', 'dispatch.view', 'Field Service', 'View dispatches and schedules.', NOW(3)),
  (UUID(), 'Create dispatch', 'dispatch.create', 'Field Service', 'Schedule and dispatch technicians.', NOW(3)),
  (UUID(), 'Edit dispatch', 'dispatch.edit', 'Field Service', 'Update field-service assignments.', NOW(3)),
  (UUID(), 'View reports', 'reports.view', 'Reporting', 'View operational reports.', NOW(3)),
  (UUID(), 'Export reports', 'reports.export', 'Reporting', 'Export report data.', NOW(3)),
  (UUID(), 'View inventory', 'inventory.view', 'Inventory', 'View parts and stock.', NOW(3)),
  (UUID(), 'View knowledge base', 'knowledge-base.view', 'Knowledge', 'View internal knowledge articles.', NOW(3)),
  (UUID(), 'View audit logs', 'audit-logs.view', 'Security', 'View audit and permission-change history.', NOW(3));
