export const CRITICAL_PERMISSION_SLUGS = [
  'users.manage',
  'roles.manage',
  'billing.manage',
  'platform-security.manage',
  'audit-logs.view',
  'backups.manage',
];

export const PERMISSION_PRESETS = [
  {
    key: 'TECHNICIAN',
    name: 'Technician',
    description: 'Work tickets, assets, dispatches, and service notes without administrative access.',
    permissionSlugs: [
      'tickets.view', 'tickets.create', 'tickets.edit',
      'assets.view', 'dispatch.view', 'dispatch.edit',
      'inventory.view', 'knowledge-base.view',
    ],
  },
  {
    key: 'DISPATCHER',
    name: 'Dispatcher',
    description: 'Coordinate ticket assignment, scheduling, field work, and customer updates.',
    permissionSlugs: [
      'tickets.view', 'tickets.create', 'tickets.edit', 'tickets.approve',
      'dispatch.view', 'dispatch.create', 'dispatch.edit',
      'users.view', 'assets.view', 'reports.view',
    ],
  },
  {
    key: 'BILLING_ADMIN',
    name: 'Billing Admin',
    description: 'Manage subscriptions, invoices, quotes, exports, and financial approvals.',
    permissionSlugs: [
      'billing.view', 'billing.create', 'billing.edit', 'billing.approve', 'billing.export',
      'invoices.view', 'invoices.create', 'invoices.edit', 'invoices.approve', 'invoices.export',
      'quotes.view', 'quotes.create', 'quotes.edit', 'quotes.approve', 'quotes.export',
    ],
  },
  {
    key: 'AUDITOR',
    name: 'Auditor',
    description: 'Read-only access to operational, billing, security, and audit evidence.',
    permissionSlugs: [
      'tickets.view', 'assets.view', 'users.view', 'billing.view', 'invoices.view',
      'reports.view', 'reports.export', 'audit-logs.view', 'platform-security.view',
    ],
  },
];

export const PERMISSION_RISK_RULES = [
  {
    key: 'billing-without-invoices',
    severity: 'warning',
    message: 'Billing management should include invoice visibility.',
    whenAll: ['billing.manage'],
    missingAny: ['invoices.view', 'billing.view'],
  },
  {
    key: 'approve-without-view',
    severity: 'warning',
    message: 'Approval privileges should include the matching view privilege.',
    pattern: '.approve',
    requiredSuffix: '.view',
  },
  {
    key: 'edit-without-view',
    severity: 'warning',
    message: 'Edit privileges should include the matching view privilege.',
    pattern: '.edit',
    requiredSuffix: '.view',
  },
  {
    key: 'delete-without-view',
    severity: 'critical',
    message: 'Delete privileges should include the matching view privilege.',
    pattern: '.delete',
    requiredSuffix: '.view',
  },
];

export const PERMISSION_DEPENDENCIES: Record<string, string[]> = {
  'tickets.create': ['tickets.view'],
  'tickets.edit': ['tickets.view'],
  'tickets.delete': ['tickets.view'],
  'tickets.approve': ['tickets.view'],
  'tickets.export': ['tickets.view'],
  'assets.create': ['assets.view'],
  'assets.edit': ['assets.view'],
  'assets.delete': ['assets.view'],
  'assets.export': ['assets.view'],
  'users.create': ['users.view'],
  'users.manage': ['users.view'],
  'users.delete': ['users.view', 'users.manage'],
  'roles.manage': ['roles.view'],
  'billing.create': ['billing.view'],
  'billing.edit': ['billing.view'],
  'billing.manage': ['billing.view', 'invoices.view'],
  'billing.approve': ['billing.view'],
  'billing.export': ['billing.view'],
  'invoices.create': ['invoices.view'],
  'invoices.edit': ['invoices.view'],
  'invoices.approve': ['invoices.view'],
  'invoices.export': ['invoices.view'],
  'quotes.create': ['quotes.view'],
  'quotes.edit': ['quotes.view'],
  'quotes.approve': ['quotes.view'],
  'quotes.export': ['quotes.view'],
  'dispatch.create': ['dispatch.view'],
  'dispatch.edit': ['dispatch.view'],
  'inventory.manage': ['inventory.view'],
  'knowledge-base.manage': ['knowledge-base.view'],
  'workflows.manage': ['workflows.view'],
  'maintenance.manage': ['maintenance.view'],
  'topology.manage': ['topology.view'],
  'security-center.manage': ['security-center.view'],
  'operations.manage': ['operations.view'],
  'catalog.create': ['catalog.view'],
  'catalog.manage': ['catalog.view'],
  'settings.manage': ['settings.view'],
  'remote-access.manage': ['remote-access.view'],
  'remote-access.launch': ['remote-access.view'],
  'patches.manage': ['patches.view'],
  'patches.deploy': ['patches.view'],
  'companies.manage': ['companies.view'],
  'reports.export': ['reports.view'],
  'email-operations.manage': ['email-operations.view'],
  'platform-security.manage': ['platform-security.view'],
  'permissions.governance.manage': ['permissions.governance.view', 'roles.view'],
  'backups.manage': ['platform-security.view'],
};

export const PERMISSION_SCOPE_TYPES = [
  { key: 'ALL', name: 'All records' },
  { key: 'ASSIGNED', name: 'Assigned records' },
  { key: 'DEPARTMENT', name: 'Department' },
  { key: 'LOCATION', name: 'Location' },
  { key: 'CUSTOMERS', name: 'Customers' },
  { key: 'RELATIONSHIP', name: 'Explicit resource relationships' },
];
